databases:
  - name: postgres
    databaseName: joestar
    user: joestar

services:
  - type: web
    name: gerenciador-de-tarefas
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
